'''
The list of suffixes in Māori sorted order
'''

regular_suffixes = (
['-a',
 '-ā',
 '-anga',
 '-hanga',
 '-hia',
 '-ia',
 '-ina',
 '-inga',
 '-kanga',
 '-kia',
 '-kina',
 '-manga',
 '-mia',
 '-na',
 '-nga',
 '-ngia',
 '-ranga',
 '-ria',
 '-tanga',
 '-tia',
 '-unga',
 '-whia',
 '-whina']
)

import collections # to convert what follows to and OrderedDict

irregular_suffixes = (
 ('ārahi', ['arahina']),
 ('awhe', ['awheawhea']),
 ('haka', ['hakā']),
 ('hanga', ['hangā']),
 ('hiki', ['hīkina']),
 ('hīpoki', ['hipokina']),
 ('homai', ['homai']),
 ('hōmai', ['hōmai']),
 ('horomi', ['horomanga']),
 ('huti', ['hūtia']),
 ('kairiri', ['kairīria']),
 ('kakati', ['katia']),
 ('kanga', ['kangā']),
 ('keuea', ['keuenga']),
 ('kokopi', ['kopia']),
 ('kokoti', ['kotia', 'kotinga']),
 ('kukume', ['kumea', 'kumenga']),
 ('kukuti', ['kutanga', 'kūtia']),
 ('kume', ['kūmea']),
 ('kuti', ['kutanga', 'kūtia']),
 ('maka', ['makā']),
 ('maoa', ['maonga']),
 ('māoa', ['maonga']),
 ('mea', ['meinga']),
 ('mimi', ['mīia']),
 ('mimire', ['mirea']),
 ('momotu', ['motuhia']),
 ('nanao', ['naomanga', 'naomia']),
 ('nanati', ['nātia']),
 ('nanatu', ['nātua']),
 ('nati', ['nātia']),
 ('noho', ['nōhia']),
 ('nuka', ['nukaia']),
 ('pae', ['pāea']),
 ('paki', ['pākia']),
 ('panga', ['pangā']),
 ('pēhi', ['pēhanga']),
 ('pēpēhi', ['pēhanga']),
 ('pepeke', ['pekenga']),
 ('pīpī', ['pīia']),
 ('pipiha', ['pihanga']),
 ('poki', ['pōkia']),
 ('popohe', ['pohenga']),
 ('popoki', ['popōkia']),
 ('popoko', ['pokonga']),
 ('puke', ['pukea']),
 ('pupuha', ['puhanga']),
 ('pupuhi', ['puhanga', 'pūhia']),
 ('pupuke', ['pukenga']),
 ('pupuri', ['purihia', 'puringa', 'puritanga', 'puritia', 'puruhia']),
 ('pupuru', ['purutanga', 'purutia']),
 ('rama', ['ramā']),
 ('ranga', ['rangā']),
 ('rapa', ['rapā']),
 ('rārā', ['rāngia']),
 ('rarahu', ['rahua']),
 ('rarama', ['ramanga']),
 ('raranga', ['rangā', 'rānga']),
 ('rarapa', ['rapanga']),
 ('rararu', ['rarunga']),
 ('rarua', ['rarunga']),
 ('raruraru', ['rarunga']),
 ('rei', ['rēinga']),
 ('rērere', ['rerenga']),
 ('ringiringi', ['ringihanga', 'ringihia']),
 ('riri', ['rīria']),
 ('ririu', ['riunga']),
 ('roiroi', ['roinga']),
 ('rongo', ['rangona', 'rongona', 'rongonga']),
 ('roroku', ['rokunga']),
 ('roromi', ['rominga']),
 ('rorotu', ['rotunga']),
 ('ruharuha', ['ruhanga']),
 ('rūnā', ['runaia', 'runā']),
 ('rūrū', ['rūrūanga']),
 ('tahutahu', ['tahunga']),
 ('taitai', ['tāia']),
 ('taiwhanga', ['taiwhangā']),
 ('taka', ['takā']),
 ('takahi', ['takahanga']),
 ('takatakahi', ['takatakahanga']),
 ('taki', ['tākina']),
 ('tapitapi', ['tāpia']),
 ('tara', ['tarā']),
 ('tarawhai', ['tarawhāia']),
 ('tatara', ['taranga']),
 ('tatari', ['tāria', 'tāringa']),
 ('tatau', ['tauanga', 'tauranga', 'tauria']),
 ('tautara', ['tautarā']),
 ('tawetawē', ['tawenga']),
 ('tāwhanga', ['tāwhangā']),
 ('tiki', ['tīkina']),
 ('titiro', ['tirohanga', 'tirohia']),
 ('toheriri', ['toherīria']),
 ('totohe', ['tohenga']),
 ('tuhituhi', ['tūhia']),
 ('tui', ['tūia']),
 ('tungi', ['tūngia']),
 ('tungu', ['tūngua']),
 ('tūtara', ['tūtarā']),
 ('tutungi', ['tūngia']),
 ('uhi', ['ūhia']),
 ('unga', ['ungā']),
 ('utiuti', ['ūtia']),
 ('wawana', ['wananga']),
 ('wawao', ['waoa', 'waonga']),
 ('wawara', ['waranga']),
 ('whai', ['whāia', 'whāinga']),
 ('whaiwhai', ['whāia']),
 ('whakahipa', ['whakahipā']),
 ('whakahīweka', ['whakahīwekā']),
 ('whakamana', ['whakamanā']),
 ('whakanoho', ['whakanōhia']),
 ('whakarere', ['whakarērea']),
 ('whakariri', ['whakarīria']),
 ('whata', ['whatā']),
 ('whitawhita', ['whitanga'])
)
irregular_suffixes = collections.OrderedDict(irregular_suffixes)
